### ISSUE TITLE
Link to team browser from Hub homepage

### ISSUE THREAD

**Issue by mtorres253** [18F/hub-v2#5]
As an 18f employee, I want to have access to the team browser so I can search for team members, or find groups of team members who match certain skill sets, or interests, so there should be a way for me to get to the team browser from the Hub homepage

Acceptance criteria
Given I am an 18f employee
When I'm viewing the homepage
Then I should see a link to the team browser
And when I click on that link, I should go to team.18f.gov

Note: this can be a link in the Recent Hires section

**Comment by mtorres253** [comment]
@jeremiak When you have time would you take a look at this?

**Comment by jeremiak** [comment]
@mtorres253 I see right now that the "See everyone" link near "Recent hires" goes to the team page on the 18F site. Would it be better if that "See everyone" link went to the team browser?

**Comment by ertzeid** [comment]
I'm only seeing one "See everyone" which is already linking to https://team.18f.gov. What is supposed to change, exactly?

Also, I'm getting a 404 at https://team.18f.gov.

**Comment by jeremiak** [comment]
@ertzeid I think that the team URL should be https://18f.gsa.gov/team/

**Comment by ertzeid** [comment]
Sounds like it should actually be https://pages.18f.gov/team-browser/, which is what I used in the PR. Thanks!
